#PostgreSQL
development:
  adapter: postgresql
  username: vadmin
  password: p@ssw0rd
  database: envelops_dev

test:
  adapter: postgresql
  username: vadmin
  password: p@ssw0rd
  database: envelops_test
